<?php

use Illuminate\Database\Seeder;

class CmsPostsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cms_posts')->delete();
        
        \DB::table('cms_posts')->insert(array (
            0 => 
            array (
                'id' => 3,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Features',
                'user_id' => NULL,
                'type' => 'Text',
                'heading' => 'features',
                'sub_heading' => 'Pemjiguj',
                'title' => 'Lorem ipsum dolor',
                'sub_title' => 'icon-home',
                'highlight' => NULL,
                'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, laboriosam.</p>',
                'description' => NULL,
                'short_description' => NULL,
                'amount' => NULL,
                'is_deleted' => 0,
                'created_at' => '2020-07-08 08:34:53',
                'updated_at' => '2020-07-11 03:41:01',
            ),
            1 => 
            array (
                'id' => 8,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Car_Company',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'Vesatu',
                'sub_heading' => 'Suafezuk',
                'title' => 'Kodhuuju',
                'sub_title' => 'Osbevwuh',
                'highlight' => '',
                'content' => '',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-09 03:49:53',
                'updated_at' => '2020-07-09 03:49:53',
            ),
            2 => 
            array (
                'id' => 9,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Car_Company',
                'user_id' => NULL,
                'type' => 'Text',
                'heading' => 'Dacjalu',
                'sub_heading' => 'Ipitevgo',
                'title' => 'Roludsaj',
                'sub_title' => 'Suvluvde',
                'highlight' => '',
                'content' => '',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-09 04:53:56',
                'updated_at' => '2020-07-09 04:53:56',
            ),
            3 => 
            array (
                'id' => 10,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Car_Company',
                'user_id' => NULL,
                'type' => 'Text',
                'heading' => 'Foloipa',
                'sub_heading' => 'Tojizo',
                'title' => 'Agkupe',
                'sub_title' => 'Jieftaz',
                'highlight' => '',
                'content' => '',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-09 04:55:50',
                'updated_at' => '2020-07-09 04:55:50',
            ),
            4 => 
            array (
                'id' => 11,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Car_Company',
                'user_id' => NULL,
                'type' => 'Image',
                'heading' => 'Lomdakca',
                'sub_heading' => 'Imbohcut',
                'title' => 'Tozvitap',
                'sub_title' => 'Mihefki',
                'highlight' => '',
                'content' => '',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-09 05:59:34',
                'updated_at' => '2020-07-09 05:59:34',
            ),
            5 => 
            array (
                'id' => 13,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Car_Company',
                'user_id' => NULL,
                'type' => 'Text',
                'heading' => 'Dimtopso',
                'sub_heading' => 'Kurnaeha',
                'title' => 'Joocevi',
                'sub_title' => 'Gobkateg',
                'highlight' => '',
                'content' => '',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-09 06:25:33',
                'updated_at' => '2020-07-09 06:25:33',
            ),
            6 => 
            array (
                'id' => 19,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Hero Banner',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'hero bannar',
                'sub_heading' => '',
                'title' => '',
                'sub_title' => '',
                'highlight' => '<p><strong>Rent&nbsp;a&nbsp;car</strong>&nbsp;is&nbsp;within&nbsp;your&nbsp;finger&nbsp;tips.</p>',
                'content' => '',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:14:40',
                'updated_at' => '2020-07-11 03:14:40',
            ),
            7 => 
            array (
                'id' => 20,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'How It Works',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'How it works?',
                'sub_heading' => '',
                'title' => 'Select a car',
                'sub_title' => '',
            'highlight' => '<p><span style="color: rgb(153, 153, 153);">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, laboriosam!</span></p>',
                'content' => '',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:31:01',
                'updated_at' => '2020-07-11 03:31:01',
            ),
            8 => 
            array (
                'id' => 21,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'How It Works',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'how it works',
                'sub_heading' => '',
                'title' => 'Fill up form',
                'sub_title' => '',
                'highlight' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, laboriosam!</p>',
                'content' => '',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:32:01',
                'updated_at' => '2020-07-11 03:32:01',
            ),
            9 => 
            array (
                'id' => 22,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'How It Works',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'how it works?',
                'sub_heading' => '',
                'title' => 'Payment',
                'sub_title' => '',
                'highlight' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, laboriosam!</p>',
                'content' => '',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:32:31',
                'updated_at' => '2020-07-11 03:32:31',
            ),
            10 => 
            array (
                'id' => 23,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Promo',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'promo',
                'sub_heading' => '',
                'title' => '',
                'sub_title' => '',
                'highlight' => '<h3><strong>You can easily avail our promo for renting a car.</strong></h3>',
                'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae, explicabo iste a labore id est quas, doloremque veritatis! Provident odit pariatur dolorem quisquam, voluptatibus voluptates optio accusamus, vel quasi quidem!</p>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:35:00',
                'updated_at' => '2020-07-11 03:35:36',
            ),
            11 => 
            array (
                'id' => 24,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Listings',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'Car Listings',
                'sub_heading' => '',
                'title' => 'Mitsubishi Pajero',
                'sub_title' => '',
                'highlight' => '',
                'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos eos at eum, voluptatem quibusdam.</p>',
                'description' => '',
                'short_description' => '',
                'amount' => '389',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:37:05',
                'updated_at' => '2020-07-11 04:34:02',
            ),
            12 => 
            array (
                'id' => 25,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Listings',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'Car Listings',
                'sub_heading' => '',
                'title' => 'Nissan Moco',
                'sub_title' => '',
                'highlight' => '',
                'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos eos at eum, voluptatem quibusdam.</p>',
                'description' => '',
                'short_description' => '',
                'amount' => '400',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:37:10',
                'updated_at' => '2020-07-11 04:34:13',
            ),
            13 => 
            array (
                'id' => 26,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Listings',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'Car Listings',
                'sub_heading' => '',
                'title' => 'Honda Fitta',
                'sub_title' => '',
                'highlight' => '',
                'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos eos at eum, voluptatem quibusdam.</p>',
                'description' => '',
                'short_description' => '',
                'amount' => '500',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:37:16',
                'updated_at' => '2020-07-11 04:34:25',
            ),
            14 => 
            array (
                'id' => 27,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Features',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'features',
                'sub_heading' => '',
                'title' => 'Lorem ipsum dolor',
                'sub_title' => 'icon-gear',
                'highlight' => '',
                'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, laboriosam.</p>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:41:51',
                'updated_at' => '2020-07-11 03:41:51',
            ),
            15 => 
            array (
                'id' => 28,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Features',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'features',
                'sub_heading' => '',
                'title' => 'Lorem ipsum dolor',
                'sub_title' => 'icon-watch_later',
                'highlight' => '',
                'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, laboriosam.</p>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:41:53',
                'updated_at' => '2020-07-11 03:42:16',
            ),
            16 => 
            array (
                'id' => 29,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Testimonials',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'testimonials',
                'sub_heading' => '',
                'title' => 'Mike Fisher',
                'sub_title' => 'Owner, Ford',
                'highlight' => '',
                'content' => '<blockquote>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, deserunt eveniet veniam. Ipsam, nam, voluptatum"</blockquote>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:43:37',
                'updated_at' => '2020-07-11 03:43:37',
            ),
            17 => 
            array (
                'id' => 30,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Testimonials',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'testimonials',
                'sub_heading' => '',
                'title' => 'Katie Rose',
                'sub_title' => ' Customer',
                'highlight' => '',
                'content' => '<blockquote>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, deserunt eveniet veniam. Ipsam, nam, voluptatum"</blockquote>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:43:40',
                'updated_at' => '2020-07-11 03:44:36',
            ),
            18 => 
            array (
                'id' => 31,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Testimonials',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'testimonials',
                'sub_heading' => '',
                'title' => 'Mike Fisher',
                'sub_title' => 'Owner, Ford',
                'highlight' => '',
                'content' => '<blockquote>"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, deserunt eveniet veniam. Ipsam, nam, voluptatum"</blockquote>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:43:42',
                'updated_at' => '2020-07-11 03:43:42',
            ),
            19 => 
            array (
                'id' => 35,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Blog',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'blog',
                'sub_heading' => '',
                'title' => '',
                'sub_title' => '',
            'highlight' => '<h2><a href="http://localhost:8000/car_rental/blog-details" rel="noopener noreferrer" target="_blank" style="color: rgb(0, 0, 0);">The best car rent in the entire planet</a></h2>',
                'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias consectetur.</p>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:47:45',
                'updated_at' => '2020-07-11 04:03:47',
            ),
            20 => 
            array (
                'id' => 36,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Blog',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'blog',
                'sub_heading' => '',
                'title' => '',
                'sub_title' => '',
            'highlight' => '<h2><a href="http://localhost:8000/car_rental/blog-details" rel="noopener noreferrer" target="_blank" style="color: rgb(0, 0, 0);">The best car rent in the entire planet</a></h2>',
                'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias consectetur.</p>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:47:48',
                'updated_at' => '2020-07-11 04:04:03',
            ),
            21 => 
            array (
                'id' => 37,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Blog',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'blog',
                'sub_heading' => '',
                'title' => '',
                'sub_title' => '',
            'highlight' => '<h2><a href="http://localhost:8000/car_rental/blog-details" rel="noopener noreferrer" target="_blank" style="color: rgb(0, 0, 0);">The best car rent in the entire planet</a></h2>',
                'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias consectetur.</p>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:47:50',
                'updated_at' => '2020-07-11 04:04:18',
            ),
            22 => 
            array (
                'id' => 38,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Car Company',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'Car Company',
                'sub_heading' => '',
                'title' => 'Car Company',
                'sub_title' => '',
                'highlight' => '',
                'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit suscipit, repudiandae similique accusantium eius nulla quam laudantium sequi.</p><p>Debitis voluptates corporis saepe molestias tenetur ab quae, quo earum commodi, laborum dolore, fuga aliquid delectus cum ipsa?</p><p><br></p>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:50:53',
                'updated_at' => '2020-07-11 04:45:26',
            ),
            23 => 
            array (
                'id' => 39,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Our Team',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'Meet Our Team',
                'sub_heading' => '',
                'title' => 'James Doe',
                'sub_title' => 'Founder',
                'highlight' => '',
                'content' => '<p class="ql-align-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, sapiente.</p>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:52:08',
                'updated_at' => '2020-07-11 03:52:08',
            ),
            24 => 
            array (
                'id' => 40,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Our Team',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'Meet Our Team',
                'sub_heading' => '',
                'title' => 'David Pitt',
                'sub_title' => 'Member',
                'highlight' => '<p class="ql-align-center"><br></p>',
                'content' => '<p class="ql-align-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, sapiente.</p>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:52:13',
                'updated_at' => '2020-07-11 03:53:41',
            ),
            25 => 
            array (
                'id' => 41,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Our Team',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'Meet Our Team',
                'sub_heading' => '',
                'title' => 'licifer combarage',
                'sub_title' => 'Member',
                'highlight' => '',
                'content' => '<p class="ql-align-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, sapiente.</p>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:52:15',
                'updated_at' => '2020-07-11 03:54:30',
            ),
            26 => 
            array (
                'id' => 42,
                'page_id' => NULL,
                'component_id' => NULL,
                'component_name' => 'Our History',
                'user_id' => NULL,
                'type' => '',
                'heading' => 'Our History',
                'sub_heading' => '',
                'title' => '',
                'sub_title' => '',
                'highlight' => '',
                'content' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit suscipit, repudiandae similique accusantium eius nulla quam laudantium sequi.</p><p>Debitis voluptates corporis saepe molestias tenetur ab quae, quo earum commodi, laborum dolore, fuga aliquid delectus cum ipsa?</p><p><br></p>',
                'description' => '',
                'short_description' => '',
                'amount' => '',
                'is_deleted' => 0,
                'created_at' => '2020-07-11 03:55:17',
                'updated_at' => '2020-07-11 04:51:42',
            ),
        ));
        
        
    }
}